INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (1, '001', 'ADMINISTRACIÓN', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (2, '002', 'ANTROPOLOGÍA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (3, '003', 'ARQUITECTURA Y URBANISMO', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (4, '004', 'ARTE', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (5, '008', 'BIOLOGÍA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (6, '011', 'CIENCIAS CONTABLES', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (7, '012', 'CIENCIAS DE LA COMUNICACIÓN SOCIAL', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (8, '013', 'CIENCIAS FÍSICO MATEMÁTICAS', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (9, '015', 'DERECHO', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (10, '034', 'EDUCACIÓN FÍSICA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (11, '035', 'EDUCACIÓN INICIAL', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (12, '036', 'EDUCACIÓN PRIMARIA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (13, '037', 'EDUCACIÓN SECUNDARIA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (14, '041', 'ENFERMERÍA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (15, '042', 'INGENIERÍA AGRÍCOLA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (16, '043', 'INGENIERÍA AGROINDUSTRIAL', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (17, '044', 'INGENIERÍA AGRONÓMICA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (18, '045', 'INGENIERÍA CIVIL', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (19, '046', 'INGENIERÍA DE MINAS', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (20, '047', 'INGENIERÍA DE SISTEMAS', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (21, '048', 'INGENIERÍA ECONÓMICA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (22, '049', 'INGENIERÍA ELECTRÓNICA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (23, '050', 'INGENIERÍA ESTADÍSTICA E INFORMÁTICA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (24, '051', 'INGENIERÍA GEOLÓGICA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (25, '052', 'INGENIERÍA MECÁNICA Y ELECTRICA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (26, '053', 'INGENIERÍA METALÚRGICA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (27, '054', 'INGENIERÍA QUÍMICA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (28, '055', 'INGENIERÍA TOPOGRÁFICA Y AGRIMENSURA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (29, '169', 'MEDICINA HUMANA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (30, '170', 'MEDICINA VETERINARIA Y ZOOTECNÍA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (31, '171', 'NUTRICIÓN HUMANA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (32, '172', 'ODONTOLOGÍA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (33, '231', 'SOCIOLOGÍA', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (34, '232', 'TRABAJO SOCIAL', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (35, '233', 'TURISMO', NULL);
INSERT INTO `careers` (`id`, `code`, `name`, `faculty`) VALUES (36, '427', 'PSICOLOGÍA', NULL);
