INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (1, 'ACONDIC.PATIO MANIOBRAS SUBU.TRANSPORTE', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (2, 'C.I.S. DE COMUNICACIONES DE LA UNA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (3, 'CENT. PROD. BS.SS.: CENT.EST. LENG.EXTR.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (4, 'CENT.DE INV.Y PROD.BS.SS.: CAMACANI', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (5, 'CENT.DE INV.Y PROD.BS.SS.: CHUCUITO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (6, 'CENT.DE INV.Y PROD.BS.SS.: CHUQUIBAMBILLA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (7, 'CENT.DE INV.Y PROD.BS.SS.: CIUDAD UNIVER', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (8, 'CENT.DE INV.Y PROD.BS.SS.: ILLPA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (9, 'CENT.DE INV.Y PROD.BS.SS.: LA RAYA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (10, 'CENT.DE INV.Y PROD.BS.SS.: MAJES', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (11, 'CENT.DE INV.Y PROD.BS.SS.: TAMBOPATA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (12, 'CENT.DE PROD. BS.SS.: CENTRO PRE UNIVERSITARIO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (13, 'CENT.DE PROD. BS.SS.: CLÍNICA ODONTOLÓGICA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (14, 'CENT.DE PROD. BS.SS.: INSTITUTO DE INFORMÁTICA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (15, 'CENT.DE PROD. BS.SS.: PANIFICAFORA Y CONFITERÍA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (16, 'CENT.DE PROD. BS.SS.: PISCINA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (17, 'CENTRO DE INVEST.Y PROD. CHUQUIBAMBILLA.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (18, 'CENTRO DE PROD.DE BS.SS.: FRIGORÍFICO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (19, 'CENTRO DE PROD.DE BS.SS.: SERVICENTRO.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (20, 'CONST.CAMPO DEPOR.SUBUNI.PROM.DEPORTE', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (21, 'CONST.COMPLEJO DEPORTIVO UNA (ESTADIO)', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (22, 'DEPARTAMENTO PSICOPEDAGÓGICO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (23, 'DIRECCION GENERAL ACADEMICA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (24, 'DIRECCION GENERAL DE ADMINISTRACION', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (25, 'DIRECCION GENERAL DE ADMISION', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (26, 'DIRECCION GENERAL DE INVESTIGACION', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (27, 'DIRECCION GRAL.DE CALID.Y ACRED.UNIV.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (28, 'DIRECCION UNIVERSITARIA ACADEMICA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (29, 'EDITORIAL UNIVERSITARIA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (30, 'ESCUELA DE POSTGRADO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (31, 'ESCUELA PROFESIONAL DE ADMINISTRACIÓN', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (32, 'ESCUELA PROFESIONAL DE ANTROPOLOGÍA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (33, 'ESCUELA PROFESIONAL DE ARQUITECTURA Y URBANISMO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (34, 'ESCUELA PROFESIONAL DE ARTE', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (35, 'ESCUELA PROFESIONAL DE BIOLOGÍA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (36, 'ESCUELA PROFESIONAL DE CIENCIAS CONTABLES', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (37, 'ESCUELA PROFESIONAL DE CS. FÍSICO MATEMÁTICO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (38, 'ESCUELA PROFESIONAL DE CS.DE LA COMUNIC.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (39, 'ESCUELA PROFESIONAL DE DERECHO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (40, 'ESCUELA PROFESIONAL DE ECONOMÍA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (41, 'ESCUELA PROFESIONAL DE EDUCACIÓN FÍSICA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (42, 'ESCUELA PROFESIONAL DE EDUCACIÓN INICIAL', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (43, 'ESCUELA PROFESIONAL DE EDUCACIÓN PRIMAR.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (44, 'ESCUELA PROFESIONAL DE ENFERMERÍA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (45, 'ESCUELA PROFESIONAL DE ING. AGROINDUSTR.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (46, 'ESCUELA PROFESIONAL DE ING. AGRONÓMICA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (47, 'ESCUELA PROFESIONAL DE ING. DE MINAS', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (48, 'ESCUELA PROFESIONAL DE ING. DE SISTEMAS', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (49, 'ESCUELA PROFESIONAL DE ING. ELECTRÓNICA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (50, 'ESCUELA PROFESIONAL DE ING. GEOLÓGICA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (51, 'ESCUELA PROFESIONAL DE ING. MECÁNICA ELÉCTRICA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (52, 'ESCUELA PROFESIONAL DE ING. METALÚRGICA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (53, 'ESCUELA PROFESIONAL DE ING. TOP.Y AGRIM.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (54, 'ESCUELA PROFESIONAL DE INGENIERÍA CIVIL', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (55, 'ESCUELA PROFESIONAL DE MEDICINA HUMANA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (56, 'ESCUELA PROFESIONAL DE MEDICINA VETERIN.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (57, 'ESCUELA PROFESIONAL DE NUTRICIÓN', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (58, 'ESCUELA PROFESIONAL DE ODONTOLOGÍA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (59, 'ESCUELA PROFESIONAL DE SOCIOLOGÍA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (60, 'ESCUELA PROFESIONAL DE TURISMO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (61, 'FAC.ING.MECAN.ELECT.ELECTRONICA Y SIST.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (62, 'FACULTAD DE CIENCIAS AGRARIAS', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (63, 'FACULTAD DE CIENCIAS BIOLOGICAS', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (64, 'FACULTAD DE CIENCIAS DE LA EDUCACION', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (65, 'FACULTAD DE CIENCIAS DE LA SALUD', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (66, 'FACULTAD DE CIENCIAS SOCIALES', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (67, 'FACULTAD DE CS. CONTABLES Y ADMINISTRAC.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (68, 'FACULTAD DE CS. JURIDICAS Y POLITICAS', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (69, 'FACULTAD DE ENFERMERIA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (70, 'FACULTAD DE INGENIERIA AGRICOLA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (71, 'FACULTAD DE INGENIERIA CIVIL ARQUITEC.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (72, 'FACULTAD DE INGENIERIA DE MINAS', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (73, 'FACULTAD DE INGENIERIA ECONOMICA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (74, 'FACULTAD DE INGENIERIA ESTADIST. E INF.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (75, 'FACULTAD DE INGENIERIA GEOLOGIA.Y METAL.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (76, 'FACULTAD DE INGENIERIA QUIMICA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (77, 'FACULTAD DE MEDICINA HUMANA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (78, 'FACULTAD DE MEDICINA VETERINARIA Y ZOOT.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (79, 'FACULTAD DE TRABAJO SOCIAL', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (80, 'MEJ. AGUA POTABLE Y SANEAMIENTO C.U.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (81, 'MEJ.AMPL.RED DE TELECOMUNICACIONES E.P.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (82, 'MEJ.SERV.FORM.PROF. ESCUELA ARTE', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (83, 'MEJ.SERV.GEST.INST.SEDE ADMINISTRATIVA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (84, 'OFICINA DE ABASTECIMIENTO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (85, 'OFICINA DE ARCHIVO CENTRAL', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (86, 'OFICINA DE ASUNTOS ACADÉMICOS Y ADMINISTRATIVOS', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (87, 'OFICINA DE AUDITORÍA ACADÉMICA E INVESTIGACIÓN', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (88, 'OFICINA DE AUDITORÍA FINANCIERA Y GESTIÓN', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (89, 'OFICINA DE BIBLIOTECA CENTRAL', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (90, 'OFICINA DE CALIDAD, LICENCIAMIENTO Y ACREDITACION', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (91, 'OFICINA DE CAPACITACIÓN DE PERSONAL ADMINISTRATIVO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (92, 'OFICINA DE COMEDORES Y RESIDENCIAS', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (93, 'OFICINA DE CONTABILIDAD', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (94, 'OFICINA DE CONTROL PREVIO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (95, 'OFICINA DE COOP.NACIONAL E INTERNAC.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (96, 'OFICINA DE COOPERAC.NACIONAL E INTERNAC.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (97, 'OFICINA DE EJECUCION DE INVERSIONES', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (98, 'OFICINA DE GESTION AMBIENTAL', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (99, 'OFICINA DE GESTIÓN DE LA CALIDAD UNIVERSITARIA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (100, 'OFICINA DE GRADOS Y TÍTULOS', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (101, 'OFICINA DE IMAGEN INSTITUCIONAL', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (102, 'OFICINA DE MEGALABORATORIOS', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (103, 'OFICINA DE PATRIMONIO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (104, 'OFICINA DE PLANEAMIENTO CURRICULAR', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (105, 'OFICINA DE PLANES Y PROYECTOS', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (106, 'OFICINA DE PRESUPUESTO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (107, 'OFICINA DE PRODUCCIÓN Y MANTENIMIENTO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (108, 'OFICINA DE PROYEC.SOCIAL Y RESPONSABIL.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (109, 'OFICINA DE PUBLICACIONES', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (110, 'OFICINA DE RACIONALIZACIÓN', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (111, 'OFICINA DE RECREACIÓN Y DEPORTE', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (112, 'OFICINA DE REGISTRO Y ARCHIVO ACADÉMICO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (113, 'OFICINA DE REMUNER., LIQUID.Y PENS.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (114, 'OFICINA DE RESOLUCIONES Y CERTIFICACIONES', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (115, 'OFICINA DE SECRETARIA GENERAL', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (116, 'OFICINA DE SERVICIO MÉDICO PRIMARIO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (117, 'OFICINA DE SERVICIO SOCIAL', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (118, 'OFICINA DE SUPERVISIÓN Y EVALUACIÓN ACADÉMICA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (119, 'OFICINA DE TECNOLOGIA E INFOR. Y TELEC.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (120, 'OFICINA DE TESORERERÍA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (121, 'OFICINA DE TRÁMITE DOCUMENTARIO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (122, 'OFICINA DE TRANSPORTES, MAQUINARIAS Y EQ', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (123, 'OFICINA DEL TRIBUNAL DEL HONOR UNIVERSITARIO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (124, 'OFICINA GENERAL DE ASESORIA JURIDICA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (125, 'OFICINA GENERAL DE CONTADURIA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (126, 'OFICINA GENERAL DE RECURSOS HUMANOS', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (127, 'OFICINA GRAL. DE PLANIFICACION Y DESAR.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (128, 'OFICINA GRAL.DE INFRAESTRUC. UNIVERSIT.', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (129, 'OFICINA UNIVERS.RECURSOS DEL APRENDIZAJE', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (130, 'RECTORADO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (131, 'UNIDAD DE DESARROLLO PERSONAL', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (132, 'UNIDAD DE SEGURIDAD, GUARDIANIA Y LIMPIEZA', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (133, 'VICERRECTORADO ACADEMICO', NULL, NULL, 1, NULL, NULL);
INSERT INTO `offices` (`id`, `name`, `description`, `ubication`, `status`, `created_at`, `updated_at`) VALUES (134, 'VICERRECTORADO DE INVESTIGACION', NULL, NULL, 1, NULL, NULL);
