INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (1, 'AUXILIAR A', '001', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (2, 'AUXILIAR C', '001', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (3, 'FUNCIONARIO F1', '001', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (4, 'FUNCIONARIO F2', '001', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (5, 'FUNCIONARIO F3', '001', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (6, 'FUNCIONARIO F4', '001', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (7, 'FUNCIONARIO F6', '001', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (8, 'PROFESIONAL A', '001', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (9, 'PROFESIONAL B', '001', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (10, 'PROFESIONAL C', '001', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (11, 'PROFESIONAL E', '001', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (12, 'TECNICO A', '001', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (13, 'TECNICO B', '001', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (14, 'TECNICO C', '001', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (15, 'MAEST.OBRA', '003', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (16, 'OFICIAL', '003', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (17, 'OPERARIO', '003', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (18, 'PEON', '003', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (19, 'ADMINISTRADOR SSI, RESPONSABLE', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (20, 'ALMACENERA', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (21, 'ALMACENERO', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (22, 'ALMACENERO DE OBRA', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (23, 'ASIST. ADMINISTRATIVO', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (24, 'ASIST. TECNICO', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (25, 'ASIST. TECNICO S. U. INFRAESTR', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (26, 'ASISTENCIA EN SALUD OCUPACIONA', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (27, 'ASISTENTE', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (28, 'ASISTENTE ADMINISTRATIVO', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (29, 'ASISTENTE ADMINISTRATIVO DE LA', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (30, 'ASISTENTE DE LIQUIDACIONES', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (31, 'ASISTENTE DE PROYECTOS', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (32, 'ASISTENTE TCNICO', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (33, 'ASISTENTE TCNICO EN ARQUITECT', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (34, 'ASISTENTE TECNICO', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (35, 'ASISTENTE TECNICO EN INSTALACI', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (36, 'ASISTENTE TECNICO SUPERVISION', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (37, 'AUXILIAR ADMINISTRATIVO', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (38, 'ESPECIALISTA EN ARQUITECTURA', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (39, 'ESPECIALISTA EN CONTROL DE CAL', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (40, 'ESPECIALISTA EN ESTRUCTURAS', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (41, 'ESPECIALISTA EN TELECOMUNICACI', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (42, 'JEFE DE LA SUB UNIDAD DE EQUIP', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (43, 'JEFE DE LA SUB UNIDAD DE INFR', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (44, 'JEFE DE LIQUIDACIONES', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (45, 'JEFE S.U.E. PROYECTISTA', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (46, 'JEFE SUB UNIDAD DE SUPERVISION', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (47, 'LIQUIDADOR FINANCIERO (ESPECIA', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (48, 'LIQUIDADOR TCNICO (ESPECIALIS', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (49, 'PREVENCIONISTA DE RIESGOS Y S', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (50, 'PREVENCIONISTA DE RIESGOS Y SE', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (51, 'RESIDENTE', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (52, 'RESIDENTE DE OBRA', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (53, 'SECRETARIA', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (54, 'SECRETARIA SUI', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (55, 'SUPERVISOR DE OBRA', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (56, 'TOPOGRAFO', '004', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (57, 'ASOCIADO D.E.', '005', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (58, 'ASOCIADO T.C.', '005', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (59, 'ASOCIADO T.P.', '005', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (60, 'AUXILIAR T.C.', '005', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (61, 'AUXILIAR T.P.', '005', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (62, 'DC DC A', '005', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (63, 'DC DC B', '005', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (64, 'JEFE PRACTICAS T.C.', '005', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (65, 'PRINCIPAL D.E.', '005', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (66, 'PRINCIPAL T.C.', '005', 1, NULL, NULL);
INSERT INTO `positions` (`id`, `name`, `type`, `status`, `created_at`, `updated_at`) VALUES (67, 'PRINCIPAL T.P.', '005', 1, NULL, NULL);
